CC = gcc

program_1: program_1.c
	$(cc) program_1.c -o program_1

program_2: program_2.c
	$(cc) program_2.c -o program_2

father: father.c
	$(cc) father.c -o father

child: child.c
	$(cc) child.c -o child
